### ISSUE TITLE
How to use Li ion 3.7v battery

### ISSUE THREAD

**Issue by hoathienvu8x** [The-Young-Maker/DIY-Tiny-ESP32-NAS#1]
Hi The Young Maker

Thanks for shared this project. I have a little issues how to use Li ion 3.7v battery

**Comment by loic-daigle** [comment]
Hi,

A lithium battery might not provide enough power for this project because both the SD cards and the ESP32 draw significant current. I encountered this issue during my design phase since the 5V to 3.3V converter wasn’t supplying sufficient current.

If you manage to find a battery with a high enough current output, you can connect it to the 5V input of the PCB. The built-in regulator will then convert it to 3.3V as needed. However, be aware that the battery, depending on its capacity, may not last very long under such a load. Additionally, there is no built-in battery charger circuit, so you would need to add your own.

I hope this helps!

**Comment by hoathienvu8x** [comment]
Hi The Young Maker

Thanks for suggestion ideas, i think Li-ion battery is backup when power is disconnected, but I'm not familiar with electronics to convert voltage.

I see a typical Nokia phone using a 3.7 Li-ion battery but I don't understand how to implement this circuit

**Comment by loic-daigle** [comment]
As I said, if you have a sufficiently powerful 3.7V lithium battery, you will only need to connect it to the 5V input (5V from USB), but be careful not to connect the battery 3 .7 V if USB is plugged in as this is probably the case. will break your battery. Additionally, to implement a circuit where the battery only powers the circuit when the USB port is unplugged, it would need to be added to the design. I might create a v2 to add this functionality, but I can't promise anything since I’m currently working on a big project.
